# Set to false to be able to capture non-tameable mobs.
capture-pets-only: true

# Set to true to be able to capture hostile mobs such as zombies, spiders, etc.
capture-monsters: false

# List of mobs that cannot be captured
mob-blacklist:
  - ender_dragon
  - wither