# Set to false to be able to capture non-tameable mobs.
capture-pets-only: true

# Set to true to be able to capture hostile mobs such as zombies, spiders, etc.
capture-monsters: false

use-blacklist-as-whitelist: false
# If above is false, list of mobs that cannot be captured
# If above is true, list of only mobs that CAN be captured
mob-blacklist:
  - ender_dragon
  - wither