name: PetTransportation
version: ${project.version}
authors: [jjm_223, Kirk Fox]
description: ${project.description}
main: me.jjm_223.pt.PetTransportation
api-version: 1.13
permissions:
  pt.*:
    description: Gives all plugin permissions
    default: op
    children:
      pt.capture: true
      pt.restore: true
      pt.override: true
      pt.capture.*: true
      pt.updatecheck: true
  pt.capture:
    description: Allows player to capture mobs in eggs
    default: true
  pt.capture.*:
    description: Allows player to capture mobs of any type
    children:
      pt.capture.pets: true
      pt.capture.passive: true
      pt.capture.monster: true
  pt.capture.pets:
    description: Allows player to capture tamed pets or foxes
    default: true
  pt.capture.passive:
    description: Allows player to capture untamed pets and passive mobs
  pt.capture.monster:
    description: Allows player to capture monsters
  pt.restore:
    description: Allows player to use spawn eggs created by the plugin
    default: true
  pt.override:
    description: Allows player to override pet ownership when capturing
  pt.updatecheck:
    description: Notifies player of a new update to the plugin