name: PetTransportation
version: ${project.version}
authors: [jjm_223, Kirk Fox]
description: Allows you to throw an egg at a pet (or other mob) to keep it in your inventory.
main: me.jjm_223.pt.PetTransportation
api-version: 1.18
permissions:
  pt.*:
    default: false
    children:
      pt.capture: true
      pt.restore: true
      pt.override: true
      pt.capture.*: true
  pt.capture:
    default: true
  pt.capture.*:
    default: false
    children:
      pt.capture.pets: true
      pt.capture.passive: true
      pt.capture.monster: true
  pt.capture.pets:
    default: true
  pt.capture.passive:
    default: false
  pt.capture.monster:
    default: false
  pt.restore:
    default: true
  pt.override:
    default: op